from typing import Dict, List, Tuple

from app.models.schemas import Chapter, NovelAnalysis, NovelMemory, RequirementPlan, ScriptScene
from app.services.scene_planner import build_scene_from_chapter


PLACEHOLDER_ACTION_PREFIXES = [
    "镜头进入旧楼，环境先给出压迫感和情绪基调。",
    "镜头进入西港，环境先给出压迫感和情绪基调。",
    "林夏、顾言围绕关键线索展开对峙，信息一层层被逼出。",
]

GENERIC_DIALOGUE = {
    "这封信是谁放在这里的？",
    "不是我。但有人想让我们都回来。",
}


def _dialogue_lines(scene: ScriptScene) -> List[str]:
    return [item.get("line", "") for item in scene.dialogue or []]


def _needs_strict_repair(current: ScriptScene, planned: ScriptScene, chapter: Chapter) -> bool:
    action_text = "\n".join(current.action or [])
    dialogue = set(_dialogue_lines(current))

    if current.title != planned.title:
        return True
    if current.location != planned.location:
        return True
    if current.time != planned.time:
        return True
    if current.conflict != planned.conflict:
        return True
    if current.purpose != planned.purpose:
        return True
    if any(prefix in action_text for prefix in PLACEHOLDER_ACTION_PREFIXES):
        return True
    if dialogue & GENERIC_DIALOGUE and chapter.order != 1:
        return True

    # 第一章不能出现第三章仓库证据。
    if chapter.order == 1 and any(word in action_text for word in ["录音笔", "保险箱", "旧手机"]):
        return True

    # 第二章必须是公司会议室/走廊，不允许复制第一章旧楼场景。
    if chapter.order == 2 and ("会议室" in chapter.text or "公司" in chapter.text):
        if current.location != "公司会议室 / 走廊" or current.title == "雨夜旧楼":
            return True
        if any("旧楼台阶" in line or "三楼门口" in line for line in current.action):
            return True

    # 第三章必须进入仓库真相，不允许复制第一章冲突目的。
    if chapter.order == 3 and ("仓库" in chapter.text or "录音笔" in chapter.text):
        if current.location != "西港十七号仓库":
            return True
        if "匿名信和照片重新打开" in current.purpose:
            return True
        if "匿名线索" in current.conflict:
            return True
        if "林建平" in current.characters:
            return True

    return False


def repair_scenes_by_chapter(
    chapters: List[Chapter],
    memory: NovelMemory,
    analysis: NovelAnalysis,
    requirement_plan: RequirementPlan,
    scenes: List[ScriptScene],
) -> Tuple[List[ScriptScene], List[str]]:
    warnings: List[str] = []
    event_map = {event.chapter_id: event for event in memory.events}
    scene_by_chapter: Dict[int, ScriptScene] = {}

    # 如果模型给了重复 source_chapter，只保留第一条，其余交给 planner 重建。
    for scene in scenes:
        if scene.source_chapter not in scene_by_chapter:
            scene_by_chapter[scene.source_chapter] = scene

    repaired: List[ScriptScene] = []

    for chapter in chapters:
        planned = build_scene_from_chapter(chapter, event_map.get(chapter.id), memory, analysis, requirement_plan)
        current = scene_by_chapter.get(chapter.order)

        if current is None:
            warnings.append(f"scene_{chapter.order:03d}: missing scene, generated by chapter-bound planner.")
            repaired.append(planned)
            continue

        if _needs_strict_repair(current, planned, chapter):
            warnings.append(f"scene_{chapter.order:03d}: strict repaired by chapter-bound planner.")
            repaired.append(planned)
        else:
            # 即使保留模型结果，也强制归一化 ID 和 source event。
            current.id = planned.id
            current.source_chapter = planned.source_chapter
            current.source_events = planned.source_events
            repaired.append(current)

    for i, scene in enumerate(repaired, start=1):
        scene.id = f"scene_{i:03d}"
        scene.source_chapter = i

    return repaired, warnings


def enforce_chapter_bound_scenes(
    chapters: List[Chapter],
    memory: NovelMemory,
    analysis: NovelAnalysis,
    requirement_plan: RequirementPlan,
    scenes: List[ScriptScene],
) -> Tuple[List[ScriptScene], List[str]]:
    """最后硬兜底：任何不匹配章节事实的核心字段都被 planner 覆盖。"""
    warnings: List[str] = []
    event_map = {event.chapter_id: event for event in memory.events}
    scene_by_chapter = {scene.source_chapter: scene for scene in scenes}
    output: List[ScriptScene] = []

    for chapter in chapters:
        planned = build_scene_from_chapter(chapter, event_map.get(chapter.id), memory, analysis, requirement_plan)
        current = scene_by_chapter.get(chapter.order)

        if current is None:
            output.append(planned)
            warnings.append(f"scene_{chapter.order:03d}: generated in final binding.")
            continue

        # 核心可读字段全部以章节 planner 为准，避免模型生成互相串场。
        changed_fields = []
        for field in ["title", "location", "time", "characters", "conflict", "purpose", "action", "dialogue", "notes", "source_events"]:
            old_value = getattr(current, field)
            new_value = getattr(planned, field)
            if old_value != new_value:
                setattr(current, field, new_value)
                changed_fields.append(field)

        current.id = f"scene_{chapter.order:03d}"
        current.source_chapter = chapter.order

        if changed_fields:
            warnings.append(f"scene_{chapter.order:03d}: final bound fields: {', '.join(changed_fields)}.")

        output.append(current)

    return output, warnings



def force_chapter_bound_final_scenes(
    chapters: List[Chapter],
    memory: NovelMemory,
    analysis: NovelAnalysis,
    requirement_plan: RequirementPlan,
) -> Tuple[List[ScriptScene], List[str]]:
    """Final hard guard.

    The final user-visible scenes must be chapter-bound.
    Model output may inform earlier passes, but if any field drifts, this function rebuilds
    every core visible field from the chapter planner.
    """
    warnings: List[str] = []
    event_map = {event.chapter_id: event for event in memory.events}
    final_scenes: List[ScriptScene] = []

    for chapter in chapters:
        planned = build_scene_from_chapter(
            chapter=chapter,
            event=event_map.get(chapter.id),
            memory=memory,
            analysis=analysis,
            requirement_plan=requirement_plan,
        )
        planned.id = f"scene_{chapter.order:03d}"
        planned.source_chapter = chapter.order
        final_scenes.append(planned)
        warnings.append(f"scene_{chapter.order:03d}: final rebuilt by chapter-bound planner.")

    return final_scenes, warnings
